legacy:
  enabled: true

global:
  image:
    pullPolicy: Always

app:
  enabled: true

  replicas: 2

  rollingUpdate:
    maxUnavailable: 50%

  ingress:
    enabled: false

  command:
    - /app/auth-service
    - run

  env:
    - name: PORT
      value: "9090"
    - name: REDIS_HOST
      value: "127.0.0.1"
    - name: REDIS_PORT
      value: "6379"
    - name: KAFKA_HOST
      value: "127.0.0.1"

  envFrom:
    - secretRef:
        name: auth-service-secret
