labels:
  domain: profile-service
  team: backend

app:
  containerPorts:
    http:
      containerPort: 9090

  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    httpGet:
      port: 9090
      path: "/healthz"

  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    httpGet:
      port: 9090
      path: "/healthz"

  service:
    type: ClusterIP
    ports:
      http:
        port: 80
